### ISSUE TITLE
accommodate methods in markdown format

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/ediutilities#9]
the file.type parameter in EMLassemblyline::template_core_metadata needs to be set to markdown
even though we don't template the methods per se (we provide a methods file), we still have to do it because otherwise it creates a methods.txt and then fails because there are two methods files.

**Comment by joannekoch** [comment]
EMLassemblyline::template_core_metadata imports abstract and methods. It does not overwrite existing files.
It writes to files only if the parameter write.file is specified, which it is not.

**Comment by joannekoch** [comment]
@sbeaulieu, I modified excel_to_template in ediutilities: EMLassemblyline::template_core_metadata(path = output_path, license = rights, file.type = ".md") to include the file.type as .md.

I tested the change using the minimal-edi-package. The call to template_core_metadata created 3 **empty** .md files: abstract, additional_info, and methods. In addition, it threw an error: "Error: Duplicate 'abstract' templates found. There can be only one." The error was because there was an abstract.md file and an abstract.txt file in the directory.

I don't understand the request for this change, especially when all was working when the file.type was defaulted to txt and there were no errors. Please explain. Your comment above: "we still have to do it because otherwise it creates a methods.txt and then fails because there are two methods files." is not true. If there is already a methods.txt file, it does not create another methods.txt file when the file.type = ".txt", nor does it overwrite it.
![Capture](https://user-images.githubusercontent.com/65416034/223712543-b9b3fa81-22de-4140-9dab-18c437a8e316.PNG)

**Comment by sbeaulieu** [comment]
Re: "the request for this change" - the request in general is to accommodate a methods file in markdown format. It would be an enhancement to our present package workflow for the methods to be provided with richer formatting than we can do with .txt. I do not know for sure if we need to change something in our utilities package or if the change would rather be in our use of emlassemblyline functions called from our Rmd.

**Comment by joannekoch** [comment]
What you are referring to is adding a parameter, file.type, to the call to excel_to_template. Excel_to_template would default the file.type to .txt when calling template_core_metadata with the passed in file.type, so existing calls would not be affected. 

I can make this change to ediutilities but it won't be used until a package calls excel_to_template with the file.type set to .md. Are there any packages that would want to use the new feature now?

Do you want me to make this change and add a new parameter?

**Comment by sbeaulieu** [comment]
I added related issue to minimal package https://github.com/WHOIGit/minimal-edi-package/issues/5

**Comment by joannekoch** [comment]
Ignore the above related issue - it is not a valid issue.
